
services:
  mysql:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Hospital5
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-initdb:/docker-entrypoint-initdb.d # Thêm dòng này
    networks:
      - hospital-network

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=Hospital5
      - DB_PORT=3306
      - PORT=4000
      - JWT_SECRET=secretkey
    networks:
      - hospital-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - hospital-network

networks:
  hospital-network:
    driver: bridge

volumes:
  mysql-data: